Feature/add category
HuyAms/expensify pull request #10
Opened 2019-09-15 14:12 UTC by vinhlee95

2019-09-16 06:03 UTC, HuyAms requested changes

2019-09-16 06:03 UTC, HuyAms commented on public/locales/en/common.json
> +	"label": {
Put this one to settings.json, under the categories section

2019-09-16 06:03 UTC, HuyAms commented on src/pages/Settings/components/CategorySettings.tsx
> +import React, {useState, useRef, useContext, useEffect} from 'react'
we should use React.useState, ...instead of importing when using the built-in Hooks

2019-09-16 06:03 UTC, HuyAms commented on src/pages/Settings/components/CategorySettings.tsx
> +	const hideCreateForm = () => {
add spacing between 2 funcs

2019-09-16 06:03 UTC, HuyAms commented on src/pages/Settings/components/CreateCategoryForm.tsx
> +		const toggleCheckbox = e => {
you can use radio button insteal of checkbox. Checkbox allows multiple choices while radio button does not

2019-09-16 06:03 UTC, HuyAms commented on src/pages/Settings/components/CreateCategoryForm.tsx
> +						<Checkbox name={type} onChange={toggleCheckbox}>
use Radio button

2019-09-16 19:38 UTC, vinhlee95 commented on src/pages/Settings/components/CategorySettings.tsx
> +import React, {useState, useRef, useContext, useEffect} from 'react'
Any reason for it?

2019-09-18 07:08 UTC, HuyAms commented on src/pages/Settings/components/CategorySettings.tsx
> +import React, {useState, useRef, useContext, useEffect} from 'react'
https://twitter.com/kentcdodds/status/1093010861961097216

I love that format too

2019-09-18 07:10 UTC, HuyAms approved these changes

2019-09-18 07:44 UTC, merged