Feature/category settings
HuyAms/expensify pull request #9
Opened 2019-09-11 19:37 UTC by vinhlee95

2019-09-12 10:12 UTC, HuyAms requested changes

2019-09-12 10:12 UTC, HuyAms commented on src/pages/Settings/index.tsx
> +const mapStateToProps = state => ({
destruct category here

const mapStateToProps = {category} =>

2019-09-12 10:12 UTC, HuyAms commented on src/pages/Settings/index.tsx
> +				data={categories.data}
could pass categories: ModuleState<Category> as a prop here

2019-09-12 10:12 UTC, HuyAms commented on src/pages/Settings/components/CategorySettings.tsx
> +				return <NotFound error={error} />
use ErrorText component when error

2019-09-12 10:12 UTC, HuyAms commented on src/pages/Settings/components/CategorySettings.tsx
> +				return <LoadingPage />
use Spinner for loading. However, I remember that Antd table has loading and error props to pass in, so use that instead

2019-09-12 10:12 UTC, HuyAms commented on src/pages/Settings/components/CategorySettings.tsx
> +	const renderCategoryItem = (data, label) => (
could rename this function to renderCategoryTable. This function could receive categoryType instead of data

```
const renderCategoryTable = (categoryType) => {
 const categories = cateogries.map({.._id, ...}).fitlter(categoryType) etc
}

```

If you do so then there is no need for sortCategoriesByType func

2019-09-12 10:12 UTC, HuyAms commented on src/pages/Settings/style.ts
> +export const Item = styled.div`
Item could be CategoryTableWrapper

2019-09-12 10:12 UTC, HuyAms commented on src/pages/Settings/components/CategorySettings.tsx
> +			switch (category.type) {
You can use map and filter for this

2019-09-12 10:12 UTC, HuyAms commented on src/components/Table/components/Cell.tsx
> +	const toggleEdit = () => setEditing(!editing)
setEditing(editing => !editing)

2019-09-12 19:45 UTC, vinhlee95 commented on src/pages/Settings/components/CategorySettings.tsx
> +	const renderCategoryItem = (data, label) => (
I will rename the function, but the point of making `sortCategoriesByType` function is that you don't have to loop through categories array to render each table. Instead, that function just does 1 loop and give back 2 array of data that needs to be rendered.

2019-09-12 19:47 UTC, vinhlee95 commented on src/pages/Settings/components/CategorySettings.tsx
> +			switch (category.type) {
Again, I just want to do 1 loop only to get proper categories to render. That's why I am using `forEach` instead of map or filter

2019-09-12 20:03 UTC, vinhlee95 commented on src/components/Table/components/Cell.tsx
> +	const toggleEdit = () => setEditing(!editing)
What is the problem in this case actually? 🤔

2019-09-13 04:23 UTC, HuyAms requested changes

2019-09-13 04:23 UTC, HuyAms commented on public/locales/en/settings.json
> +			"heading": {
Imo, we should flat the json

```
{
	"title": "Settings",
	"categories": {
		"title": "Categories",
		"expenseLabel": "Expense categories",
		"incomeLabel": "Income categories",
		"name": "Name",
                "description": "Description"
}
}
```

2019-09-13 04:23 UTC, HuyAms commented on src/components/Table/components/Cell.tsx
> +	const toggleEdit = () => setEditing(!editing)
if you want to change the state based on the previous state, you should use a callback. In this case it works fine but if we continue to develop, it could raise a bug

2019-09-13 04:23 UTC, HuyAms commented on src/pages/Settings/components/CategorySettings.tsx
> +				return <Spinner />
Ant table has loading props, so in this case, check error and success is enough. Then pass the loading to the Table like below
<Table loading={status === 'fetching'}

2019-09-13 04:23 UTC, HuyAms commented on src/pages/Settings/index.tsx
> +				data={categories.data}
Update this one

2019-09-13 04:23 UTC, HuyAms commented on src/pages/Settings/components/CategorySettings.tsx
> +					return
could throw an error, category type not supported

2019-09-13 06:46 UTC, HuyAms approved these changes

2019-09-13 06:46 UTC, merged